/**
 * Canonical wire-level type definitions and constraint constants shared across
 * the Cards V2 ecosystem. Defines the JSON-serializable shapes for cards,
 * REST API requests and responses, WebSocket domain events,
 * webview communication, settings, and validation boundaries.
 *
 * Most of this surface is types and constants alone. The runtime protocol
 * exported at the end is the exception: it carries validated schemas and the
 * delivery, transition, and authorization tables, because both the server and
 * every client must agree on those rules and neither can be their owner.
 *
 * @summary Shared protocol types, constants, and the runtime protocol contract for the Cards V2 wire format
 * @module
 */

export type {
  Action,
  ActionClientMessage,
  ActionMessage,
  ActionResult,
  ActionState,
  ActionSummaryResponse,
  ActivityStateResponse,
  AddBranchRequest,
  AddBranchResponse,
  AddCommitRequest,
  AdmissionRejectionReason,
  AdmissionScope,
  AdmissionUncertaintyReason,
  AdmittedLaunchCredentials,
  ApiError,
  ApiRequestMessage,
  ApiResponseMessage,
  ApiSuccess,
  AsyncFileExistsCallback,
  AsyncListFilesCallback,
  AsyncReadFileCallback,
  AsyncWriteFileCallback,
  AttachmentAddedEvent,
  AttachmentInfoFile,
  AttachmentRemovedEvent,
  AttachmentResponse,
  BoundExecution,
  BranchesResponse,
  BranchInfo,
  BranchRegistrationIntent,
  CancelAcknowledgment,
  CancelCommand,
  Card,
  CardCommit,
  CardCommitDiffUnavailable,
  CardCommitEvent,
  CardCommitFile,
  CardCreatedEvent,
  CardCreateGates,
  CardDeletedEvent,
  CardDetailMessage,
  CardGates,
  CardIncomingRelationsChangedEvent,
  CardJournalClientMessage,
  CardJournalEntry,
  CardJournalEventMessage,
  CardJournalServerMessage,
  CardMetadata,
  CardPostCommitRequest,
  CardPostCommitResponse,
  CardRelation,
  CardRelationType,
  CardReplayMessage,
  CardResponse,
  CardSnapshot,
  CardSnapshotMessage,
  CardStatus,
  CardSubscribeFailedMessage,
  CardSubscribeMessage,
  CardsApiInfo,
  CardsAssistant,
  CardsMetadataEvent,
  CardUnsubscribeMessage,
  ClientLaunchAdmission,
  CodingAgentId,
  CollectedResourceReference,
  Command,
  Comment,
  CommentCreatedEvent,
  CommentTimelineItem,
  CommitAttributionResponse,
  CommitAuthor,
  CommitDetails,
  CommitStats,
  CommitTimelineItem,
  CompareBranchRangeRequest,
  CompareChangedEvent,
  CompareClearedEvent,
  CompareDynamicRequest,
  CompareFixedAttributionRequest,
  CompareMode,
  CompareRequest,
  CompareState,
  ConnectionsResponse,
  CreateAttachmentRequest,
  CreateCardRequest,
  CredentialRefusalReason,
  DomainEvent,
  ElementSpan,
  Environment,
  EnvironmentInfo,
  EnvironmentsResponse,
  EventMessage,
  ExecutionMode,
  ExtensionToWebviewMessage,
  FieldError,
  FileChange,
  FileExistsCallback,
  GateApprovalResponse,
  GateName,
  HasUpdatesResponse,
  HealthResponse,
  HookConfig,
  HookEvent,
  HookScript,
  HtmlContentCheckResult,
  HtmlCssSource,
  HtmlDocumentFacts,
  HtmlFileCspPolicyOptions,
  HtmlInfoFile,
  HtmlInfoValidationResult,
  HtmlInlineEventHandler,
  HtmlIntrinsicLayoutCheckResult,
  HtmlIntrinsicLayoutInputs,
  HtmlStylesheetReference,
  HttpClient,
  ImmutableActionParams,
  IssuedRoleCredential,
  LaunchAdmissionRefusal,
  LaunchAdmissionRequest,
  LaunchClaudeAction,
  LaunchOutcome,
  ListCardsRequest,
  ListFilesCallback,
  ListTagsRequest,
  MergeStatusSnapshot,
  MergeStatusValue,
  NavigateMessage,
  NotificationCreateRequest,
  NotificationSeverity,
  OriginalCallerRequestId,
  PlanDriftValue,
  PresentedCredential,
  ProcessState,
  ReadFileCallback,
  RemoveBranchRequest,
  RemoveBranchResponse,
  ReplayedLaunchAdmission,
  ResourceReferenceClass,
  RetrievedAdmission,
  ScriptSpan,
  ServerChangedMessage,
  SessionBaseline,
  SessionType,
  Settings,
  SpawnPhase,
  StateUpdateMessage,
  StreamDefinition,
  StreamEndedEvent,
  StreamErrorEvent,
  StreamLineEvent,
  StreamMeta,
  StreamMetaFile,
  StreamResumedEvent,
  StreamStartedEvent,
  SwitchToInteractiveCommand,
  TagsResponse,
  ThemeUpdateMessage,
  TimelineCommentAddedEvent,
  TimelineCommentRemovedEvent,
  TimelineCommentUpdatedEvent,
  TimelineCommitAddedEvent,
  TimelineCommitRemovedEvent,
  TimelineItem,
  TimelineRequest,
  TimelineResponse,
  UpdateCardRequest,
  ValidationErrorCode,
  ValidationErrorMessage,
  VariableGroupListRequestEvent,
  VariableGroupListResultEvent,
  VariableGroupSummary,
  VariableGroupsResponse,
  WebviewAction,
  WebviewDidConnectMessage,
  WebviewState,
  WebviewTimelineEntry,
  WebviewToExtensionMessage,
  WorkspaceBranch,
  WorkspaceCommitEvent,
  WorkspacePostCommitRequest,
  WorkspacePostCommitResponse,
  WrapperCommand,
  WrapperErrorResponse,
  WrapperResponse
} from './types/index.js';
// --- Runtime Protocol ---
export {
  type AuthorizationContext,
  type AuthorizationOutcome,
  type AuthorizationRefusalReason,
  assertSupportedProtocolVersion,
  authorizeMessage,
  authorizeTermination,
  BASE_ELEMENT_TAG_NAMES,
  BRANCHES_DIR,
  buildHtmlFileCspPolicy,
  CARD_RELATION_TYPES,
  CODING_AGENT_IDS,
  COMMITS_DIR,
  CONNECTION_STATES,
  CONNECTION_TRANSITIONS,
  CONNECTION_TRIGGERS,
  type ConnectionGeneration,
  type ConnectionSlotKey,
  type ConnectionState,
  type ConnectionSubject,
  type ConnectionTransition,
  type ConnectionTrigger,
  canRetireDurableResult,
  checkHtmlContent,
  checkIntrinsicHtmlLayout,
  classifyResourceReference,
  collectResourceReferences,
  compareOwnership,
  connectionGenerationSchema,
  connectionSlotKeySchema,
  connectionStateSchema,
  connectionSubjectSchema,
  DEFAULT_CARD_GATES,
  DELIVERY_CLASS_POLICIES,
  DELIVERY_CLASSES,
  type DeliveryClass,
  type DeliveryClassPolicy,
  type DeliveryDecision,
  type DeliveryDisposition,
  type DurableIntentRecord,
  type DurableResultRecord,
  deliveryClassFor,
  deliveryClassSchema,
  EMPTY_TREE_SHA,
  type EnvelopeRejectionReason,
  EnvelopeValidationError,
  EXECUTION_LIFECYCLE_STATES,
  EXECUTION_LIFECYCLE_TRANSITIONS,
  type ExecutionIdentity,
  type ExecutionLifecycleState,
  type ExecutionRef,
  type ExecutionRequirement,
  envelopeHeaderSchema,
  evaluateDisposableTelemetry,
  evaluateDurableIntent,
  evaluateDurableResult,
  evaluateReadinessReceipt,
  evaluateReconciledSnapshot,
  executionIdentitySchema,
  executionLifecycleStateSchema,
  executionRefSchema,
  FRAME_ELEMENT_TAG_NAMES,
  FRAME_REFUSAL_REASONS,
  type FrameRefusalReason,
  filterStructuralParseErrors,
  findConnectionTransition,
  findLifecycleTransition,
  frameRefusalReasonSchema,
  htmlCardDocPathForSidecar,
  htmlCardDocSidecarPath,
  INFORMATIONAL_PARSE5_CODES,
  INITIAL_CONNECTION_GENERATION,
  isAdmittedExecution,
  isCodingAgentId,
  isHtmlCardDocPath,
  isHtmlCardDocSidecarPath,
  LIFECYCLE_GUARDS,
  type LifecycleGuard,
  type LifecycleTransition,
  type LifecycleTrigger,
  launchRequestPayloadSchema,
  MAX_CONTROL_FRAME_BYTES,
  MAX_ID_LENGTH,
  MAX_OUTSTANDING_MESSAGES,
  MAX_SUMMARY_LENGTH,
  MAX_TAG_LENGTH,
  MAX_TITLE_LENGTH,
  type MessageContract,
  type MessageDirection,
  type OwnershipComparison,
  type OwnershipStamp,
  ownershipStampSchema,
  PRODUCER_ROLES,
  type ProducerIdentity,
  type ProducerRole,
  parseEnvelope,
  producerIdentitySchema,
  producerRoleSchema,
  protocolVersionSchema,
  REGISTRATION_REFUSAL_REASONS,
  type ReadinessRecord,
  type RegistrationOutcome,
  type RegistrationRefusalReason,
  RUNTIME_CREDENTIAL_HEADERS,
  RUNTIME_MESSAGE_CONTRACTS,
  RUNTIME_MESSAGE_PAYLOADS,
  RUNTIME_MESSAGE_TYPES,
  RUNTIME_PROTOCOL_VERSION,
  RUNTIME_UPGRADE_PATH,
  type RuntimeEnvelope,
  type RuntimeMessageType,
  type RuntimePayload,
  type RuntimeScope,
  registrationOutcomeSchema,
  registrationRefusalReasonSchema,
  runtimeMessageTypeSchema,
  runtimeScopeSchema,
  type SnapshotStamp,
  SUPPORTED_PROTOCOL_VERSIONS,
  TAG_PATTERN,
  TERMINAL_LIFECYCLE_STATES,
  type TelemetryBufferState,
  type TerminationAuthorization,
  type TerminationAuthorizationInput,
  type TerminationRefusalReason,
  UnsupportedProtocolVersionError,
  validateHtmlInfo
} from './types/index.js';
// --- Status Types ---
// --- Card Types ---
// --- API Discovery Types ---
// --- Response Envelope Types ---
// --- WebSocket Event Types ---
// --- Webview Messaging Types ---
// --- Custom Types ---
// --- API Request/Response Types ---
// --- Remote Programmatic API Types ---
// --- Input Constraints ---
// --- Card Gates ---
// --- Runtime Protocol: Launch Admission ---
export {
  CHILD_RUNTIME_CREDENTIAL_ROLES,
  type ChildRuntimeCredentialRole,
  type RuntimeCredentialFile,
  runtimeCredentialFileSchema
} from './types/runtime-credential-file.js';
